In [ ]:
import numpy as np
array1D=np.array([1,2,3])
print(array1D)

[1 2 3]


In [ ]:
array2d=np.array([[1,2],[3,4]])
print(array2d)

[[1 2]
 [3 4]]


In [ ]:
zeros_array=np.zeros((2,3))
print(zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
array=np.array([1,2,3],dtype='float32')
print(array)

[1. 2. 3.]


In [ ]:
array=np.array([10,20,30,40])
print(array[1])

20


In [ ]:
array = np.arange(6)
reshaped = array.reshape(2, 3)
print(reshaped)

[[0 1 2]
 [3 4 5]]


In [ ]:
print(np.arange(100))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


NUMPY part 2

In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=a+b
print(c)

[5 7 9]


In [ ]:
array=np.array([1,2,3,4])
print(np.sum(array))
print(np.mean(array))
print(np.std(array))
print(np.var(array))
print(np.min(array))
print(np.max(array))
print(np.argmin(array))
print(np.argmax(array))

10
2.5
1.118033988749895
1.25
1
4
0
3


In [ ]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
print(np.dot(a,b))

[[19 22]
 [43 50]]


In [ ]:
a = np.array([1, 2, 3])
b = np.array([[10], [20]])
print(a + b)

[[11 12 13]
 [21 22 23]]


In [ ]:
a = np.array([[1], [2], [3]])
b = np.array([10, 20, 30])
print(a + b)

[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [ ]:
data=np.array([1,2,3,4,5])
norm=(data-np.min(data))/(np.max(data)-np.min(data))
print(norm)

[0.   0.25 0.5  0.75 1.  ]


In [ ]:
a=np.array([1,2,3,4,5])
b=a[2:8]
b[0]=100
print(a)
print(b)

[100   4   5]


3x+2y=9
x+2y=8
Ax=b

In [ ]:
a=np.array([[3,1],[1,2]])
b=np.array([[9],[8]])
print(np.linalg.solve(a,b))

[[2.]
 [3.]]
